galaxy_info:
  role_name: module_test
  namespace: beatljs
  author: Sergey Zhukov
  description: Testing my own module
  company: Netology_DevOps_32
  license: MIT

  min_ansible_version: "2.8"

  platforms:
    - name: Debian
      versions:
        - buster
    - name: EL
      versions:
        - 'all'

  galaxy_tags:
    - module_test

dependencies: []
